### PR TITLE
Fix datarace

### LINKED ISSUE #137: Data race in dmsgdirect
**Describe the bug**
Data race on starting visor on dmsghttp.
```
==================
WARNING: DATA RACE
Write at 0x00c000340030 by goroutine 18:
  github.com/skycoin/dmsg/direct.(*directClient).PostEntry()
      /home/erson/Workspace/Go/skywire/vendor/github.com/skycoin/dmsg/direct/client.go:78 +0x6a6
  github.com/skycoin/skywire/pkg/visor.getHTTPClient()
      /home/erson/Workspace/Go/skywire/pkg/visor/init.go:1100 +0x415
  github.com/skycoin/skywire/pkg/visor.initDmsg()
      /home/erson/Workspace/Go/skywire/pkg/visor/init.go:309 +0x110
  github.com/skycoin/skywire/pkg/visor.withInitCtx.func1()
      /home/erson/Workspace/Go/skywire/pkg/visor/init.go:1071 +0xce
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:139 +0x4d6
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent·dwrap·4()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:117 +0x58

Previous read at 0x00c000340030 by goroutine 21:
  github.com/skycoin/dmsg.getClientEntry()
      /home/erson/Workspace/Go/skywire/vendor/github.com/skycoin/dmsg/entity_common.go:291 +0xd9
  github.com/skycoin/dmsg.(*Client).DialStream()
      /home/erson/Workspace/Go/skywire/vendor/github.com/skycoin/dmsg/client.go:267 +0xb2
  github.com/skycoin/dmsg/dmsghttp.HTTPTransport.RoundTrip()
      /home/erson/Workspace/Go/skywire/vendor/github.com/skycoin/dmsg/dmsghttp/http_transport.go:38 +0x2bd
  net/http.send()
      /usr/local/go/src/net/http/client.go:252 +0x93e
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:176 +0x157
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:725 +0x1086
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:593 +0x587
  github.com/skycoin/skywire/internal/httpauth.(*Client).Nonce()
      /home/erson/Workspace/Go/skywire/internal/httpauth/client.go:174 +0x55e
  github.com/skycoin/skywire/internal/httpauth.NewClient()
      /home/erson/Workspace/Go/skywire/internal/httpauth/client.go:76 +0x3c4
  github.com/skycoin/skywire/internal/utclient.NewHTTP.func1()
      /home/erson/Workspace/Go/skywire/internal/utclient/client.go:60 +0x184
  github.com/skycoin/skywire/internal/netutil.Retrier.retryNTimes()
      /home/erson/Workspace/Go/skywire/internal/netutil/retrier.go:65 +0xe2
  github.com/skycoin/skywire/internal/netutil.Retrier.Do()
      /home/erson/Workspace/Go/skywire/internal/netutil/retrier.go:58 +0x144
  github.com/skycoin/skywire/internal/utclient.NewHTTP()
      /home/erson/Workspace/Go/skywire/internal/utclient/client.go:67 +0x27d
  github.com/skycoin/skywire/pkg/visor.initUptimeTracker()
      /home/erson/Workspace/Go/skywire/pkg/visor/init.go:768 +0x2c4
  github.com/skycoin/skywire/pkg/visor.withInitCtx.func1()
      /home/erson/Workspace/Go/skywire/pkg/visor/init.go:1071 +0xce
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:139 +0x4d6
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent·dwrap·4()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:117 +0x58

Goroutine 18 (running) created at:
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:117 +0x21b
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent·dwrap·4()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:117 +0x58

Goroutine 21 (running) created at:
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:117 +0x21b
  github.com/skycoin/skywire/pkg/visor/visorinit.(*Module).InitConcurrent·dwrap·4()
      /home/erson/Workspace/Go/skywire/pkg/visor/visorinit/module.go:117 +0x58
==================
```

### PR DESCRIPTION
**Pull request by ersonp**
Fixes #137

 Changes:	
- Updated the func PostEntry()
- Replaced the variable `e` with `entry` in the funcs of `APIClient`

How to test this PR:
Check [#skywire-1033](https://github.com/skycoin/skywire/pull/1033)

### CODE REVIEW

File: direct/client.go [hunk 1]
```diff
@@ -43,41 +43,18 @@ func (c *directClient) Entry(ctx context.Context, pubKey cipher.PubKey) (*disc.E
 }
 
 // PostEntry adds a new Entry.
-func (c *directClient) PostEntry(ctx context.Context, e *disc.Entry) error {
+func (c *directClient) PostEntry(ctx context.Context, entry *disc.Entry) error {
```
Comment (jdknives) [inline direct/client.go:48]: This function cant really return an error anymore so leaving the function signature as is seems misleading. Also `PostEntry` seems to imply that we make some networked request which is not the case.

**Review by jdknives — COMMENTED** [review]
Cant test the change right now. Just a small comment.

File: direct/client.go (hunk 1 above)
Comment (ersonp) [reply direct/client.go:48]: I'm using the [APIClient](https://github.com/ersonp/dmsg/blob/5eea5d6365c70c3f7e05b7bcfd1dd56eeffa0add/disc/client.go#L22) interface for it so that it will be used as a memory version of the `dmsg-discovery`.

Comment (ersonp) [reply direct/client.go:48]: One way to fix the naming issue will be to change the func names in [APIClient interface](https://github.com/ersonp/dmsg/blob/5eea5d6365c70c3f7e05b7bcfd1dd56eeffa0add/disc/client.go#L22) to 
```
PostEntry -> SaveEntry
PutEntry -> UpdateEntry
```
And use private funcs `postEntry` and `putEntry` in the `disc` inside of `SaveEntry` and `UpdateEntry` respectively. Also, the function signature will be the same as we have for `Redis` and `memory` store in services where the funcs in the `memory store` don't return any errors.
