### PR TITLE
Fix wrong current client and server connected

### LINKED ISSUE #119: Metric for current connected client counter
**Describe the bug**
We need a metric for count/return the number of connected clients. (Related to skywire-services issue [#460](https://github.com/SkycoinPro/skywire-services/issues/460))

### PR DESCRIPTION
**Pull request by mrpalide**
Fixes #119 

 Changes:	
- set `delEntry` on close servers
- remove *pubkey* on `delEntry` from **servers** OR **clients** set store in Redis db.
- set expire timeout on server type entries, and add routine for  delete old entries on `servers` set record.

How to test this PR:
- run dmsg-discover and dmsg-server (suggest to run 2 server) as test (following [these](https://github.com/skycoin/dmsg/tree/develop/integration) steps).
- on develop@skywire, generate a config and replace dmsg discovery address with `http://localhost:9090`
- run the visor
- check redis for keys
- close visor or server and check redis again.

### CODE REVIEW

**Review by jdknives — COMMENTED** [review]
@mrpalide a few notes about your PR:

1. We do not need a new endpoint for the discovery. We already have a `metrics` endpoint where we should expose this data, but the data is faulty. 

2. We do not need a new field in the entry. We need two pieces of information that are 

- how many clients are currently registered in the discovery
- how many servers are currently registered in the discovery

Both pieces of information should be exposed in the metrics endpoint and not require any modification for the server/client at all.

File: cmd/dmsg-discovery/internal/store/redis.go [hunk 1]
```diff
@@ -60,6 +61,10 @@ func (r *redisStore) SetEntry(ctx context.Context, entry *disc.Entry, timeout ti
 		return disc.ErrUnexpected
 	}
 
+	if entry.Server != nil {
+		timeout = dmsg.DefaultUpdateInterval
```
Comment (jdknives) [inline cmd/dmsg-discovery/internal/store/redis.go]: We should probably set this value a little but higher in case there is some latency, right?

Comment (mrpalide) [reply cmd/dmsg-discovery/internal/store/redis.go]: You're right. I set it to 5 minutes.
